### ISSUE TITLE
CLI switch of --rm to destroy volume after stopping container

### ISSUE THREAD

**Issue by hekaldama** [yp-engineering/rbd-docker-plugin#12]
Add new CLI switch to "--rm" the volume after stopping container. Used namely in testing.

**Comment by ps-account** [comment]
Thanks! Maybe rm is confusing, make it an option to mount as "non-persistent"  instead. 

On a similar note, I think I don't really understand this part in the readme file: 

Remove - Removes (destroys) RBD Image on request
only called for docker run --rm -v ... or docker rm -v ... container
controlled by --remove boolean flag (default false)
if remove is true -> image is removed
if remove is false -> image is renamed with zz prefix for later culling

I tried to run a docker with --rm and mounting a new ceph volume, but after exiting the instance nothing seems to have happened to the newly created ceph volume?

**Comment by hekaldama** [comment]
Oh. Seems like the plugin itself needs to be configured to allow remove so when starting the volume plugin, do `--remove=true` to allow for this behavior. Does this help your use case?

**Comment by porcupie** [comment]
Can this be closed now?
