### ISSUE TITLE
Question: How to run the plugin on CoreOS / with Ceph cluster on Docker

### ISSUE THREAD

**Issue by tobilg** [yp-engineering/rbd-docker-plugin#18]
Are there any hints on how to run the `rbd-docker-plugin` on CoreOS?

We run a fully Dockerized Mesos and Ceph environment, and for using stateful containers, we'd like to use Docker volumes on Ceph. As far as I understand the installation of this plugin requires the some libraries to be present on the host system. 

As CoreOS works a little different then CentOS/Debian/etc., is there a way to run the plugin within a container itself? If no, how would I otherwise be able to use it on CoreOS?

**Comment by tobilg** [comment]
Anybody?

**Comment by h0tbird** [comment]
Basically you have to containerize the plugin and all its runtime dependencies.
If you choose Docker as your container runtime (for the plugin) you might run into some chicken-egg problems. I recommend using `systemd-nspawn` or `rkt fly` as container runtimes for docker plugins.

**Comment by tobilg** [comment]
@h0tbird Thanks! I posted a [similar question](https://github.com/contiv/volplugin/issues/103) to `contiv/volplugin`, and it seems like `rkt fly stage1` is the preferred way of doing this, as suggested by CoreOS members.

**Comment by hekaldama** [comment]
Thanks @h0tbird for chiming in. @tobilg, I am going to close, but please feel free to reopen if needed.
