### ISSUE TITLE
Replace RBD shell commands with RBD kernel object operations

### ISSUE THREAD

**Issue by h0tbird** [yp-engineering/rbd-docker-plugin#2]
I know this one is hard but not every target system has `/usr/bin/rbd` available (such as CoreOS).
The kernel driver has an entry point here `/sys/bus/rbd` and functions are described [here](http://ceph.com/docs/argonaut/rbd/rbd-ko/).

**Comment by hekaldama** [comment]
Sorry, I am git grepping around and not seeing mention of this path anywhere. Where are you looking?

**Comment by h0tbird** [comment]
Sorry, the path is not hard-coded anywhere inside the code but you have lines such as:

```
sh("rbd", "map", "--pool", pool, imagename)
sh("rbd", "unmap", device)
sh("rbd", "rm", "--pool", pool, name)
```

which are using the system-wide `rbd` binary. And my point is that not every system will have this binary available.

**Comment by hekaldama** [comment]
Okay. Thanks for looking at all this stuff! As always, feel free to send pull requests with fixes as well.

**Comment by porcupie** [comment]
Ah - thanks @h0tbird, great suggestion!  I had not seen that /sys interface and will definitely look into how to implement this.  Looks like I will also need to pass the cephx keypath and know the mon address.

**Comment by hekaldama** [comment]
Note, there are other versions of the docs mentioned above as well. The original is to the Ceph 'argonaut' release, we may want to look at the latest docs too for hammer: http://ceph.com/docs/hammer/rbd/rbd-ko/

**Comment by h0tbird** [comment]
Looks like the `/sys` interface is not documented for hammer.
This is bad for the purpose of this issue.
I wonder how the other ceph drivers handle rbd operations.

**Comment by h0tbird** [comment]
> Package librbd provides functionality to interact with Ceph RADOS block device (RBD)
> subsystem and underlying kernel support. It requires the librados and librbd
> libraries to function.

Using `librbd` seems the right thing to do.

**Comment by porcupie** [comment]
@h0tbird : is the `librbd` you refer to the one inside the volplugin codebase?

Also wondering if it is possible to get features in go-ceph, though I have not yet reached out to them.

**Comment by erikh** [comment]
hi folks, the C librbd (from ceph) doesn't handle the krbd stuff. You need that doc above, or the go librbd from the volplugin project can help.

I'll see what I can do about getting this extracted later tonight so you can at least play with it easily.

**Comment by h0tbird** [comment]
I agree that a contribution to `go-ceph` with the `volplugin` rbd mapping code is the best way to share it.

**Comment by erikh** [comment]
oh, fwiw, the doc is incorrect in a few spots. If you do choose to re-implement it, you might want to look at the librbd stuff anyway, just to figure it out. It's commented. :D

**Comment by erikh** [comment]
Additionally be careful with the config; the multi-level configs that some ceph installations cannot be processed by librados, so you'll need to finagle that configuration separately.

I hope this is helpful context, and not just spam :)

**Comment by porcupie** [comment]
Thanks so much for your work (also in advance for help with librbd) @erikh, very helpful comments as well.  Looking forward to getting this implemented and avoiding shell out to rbd binary.

**Comment by leseb** [comment]
FWIW I don't think we should replace this completely. I think we should check for a 'rbd' binary first and then fallback to the "echo >" method if nothing is found.

**Comment by leseb** [comment]
Just missed some comments, using librbd seems to be the best thing to do.
@h0tbird coreOS doesn't seem to have the librbd, how would you manage that?

**Comment by leseb** [comment]
Looks like this is what we would like to do here (if not librbd) https://github.com/contiv/volplugin/blob/master/librbd/image.go#L105-L171

**Comment by h0tbird** [comment]
@porcupie, @leseb: by `librbd` I was thinking about the one inside `volplugin` not the C one provided by the Ceph project. Also by "volplugin rbd mapping code" I basically mean the code highlighted in the previous @leseb  comment. I also agree that the fail-over mechanism is a good idea.

And thinking about @leseb comment on the lack of C `librbd` in CoreOS. I think it is possible to statically link C code inside Go code (if it is ever needed).

**Comment by leseb** [comment]
@h0tbird ok clearer now :)

**Comment by hekaldama** [comment]
@h0tbird @leseb @porcupie @erikh I am hanging out on IRC freenode #yp-engineering channel if you want to chat about things ever. I am usually online 7am-3pm PST.

**Comment by h0tbird** [comment]
I have figured out a way to use `rbd` in a CoreOS host using the following bash wrapper script:

```
core@core-1 ~ $ cat /opt/bin/rbd 
#!/bin/bash
docker run -i --rm \
--privileged \
--pid host \
--name rbd \
--net host \
--volume /dev:/dev \
--volume /sys:/sys \
--volume /etc/ceph:/etc/ceph \
ceph/base rbd $@
```

The trickiest part is `--pid host` which prevents RBD lock collisions because:
- Records in 'ceph osd blacklist ls' consist of an IP, a port and a
  nonce — so essentially unique per-process.
- I think the nonce is computed using the current rbd PID so same PID
  implies same nonce.
- Inside a container PID is always 1 so we have lock collisions.

As far as I'm concerned feel free to close this ticket. I am working on a CoreOS-aware version of this plugin.

**Comment by hekaldama** [comment]
Will still look into where ceph has come to and if librbd has come farther.
