### ISSUE TITLE
Add Get/List RPC calls

### ISSUE THREAD

**Issue by cpuguy83** [yp-engineering/rbd-docker-plugin#21]
Docker 1.10 adds 2 new calls to the volume API, `Get` and `List`.
In order to make this plugin work with Docker 1.10 you should support these two new calls.

**Comment by hekaldama** [comment]
@cpuguy83 are you referring to https://docs.docker.com/engine/reference/api/docker_remote_api_v1.21/#2-4-volumes ?

**Comment by cpuguy83** [comment]
Referring to `Get` and `List` here: https://github.com/docker/docker/blob/master/docs/extend/plugins_volume.md

**Comment by hekaldama** [comment]
Thanks.

**Comment by hekaldama** [comment]
Been working on a mesos framework. Will try and get to these soon. PRs are always welcome ;)

**Comment by hekaldama** [comment]
Try latest and see if that fixes you. If not, reopen with details. Thanks!
