### ISSUE TITLE
problem with docker 1.10

### ISSUE THREAD

**Issue by nidorpi** [yp-engineering/rbd-docker-plugin#23]
Hi,
I try to use rbd plugin but unfortunately I've error like this: 

```
go get github.com/yp-engineering/rbd-docker-plugin

src/github.com/yp-engineering/rbd-docker-plugin/main.go:83: cannot use d (type cephRBDVolumeDriver) as type volume.Driver in function argument:
        cephRBDVolumeDriver does not implement volume.Driver (missing Get method)
```

It's fresh installation of ubuntu 14.04 but on ubuntu 15.10 I've the same error. Any idea how to resolve this ? 

--- edit

after analyzing code other pluggins I see that file driver.go should implement method :

```
func (d cephRBDVolumeDriver) Get(r dkvolume.Request) dkvolume.Response { ... }
func (d cephRBDVolumeDriver) List(r dkvolume.Request) dkvolume.Response { ... }
```

**Comment by hekaldama** [comment]
relates to #21. Been working on a mesos framework. Will try and get to these soon. PRs are always welcome ;)

**Comment by zhubingbing** [comment]
Me too， how to resolve this ?

**Comment by nidorpi** [comment]
zhubingbing, I wrote this two functions and compile plugin again

**Comment by zhubingbing** [comment]
Be able to share the next？，I don‘t know to write。

**Comment by hekaldama** [comment]
Try latest and see if that fixes you. If not, reopen with details. Thanks!

**Comment by ebertech** [comment]
Hi, still getting them same thing...

**Comment by alfredcs** [comment]
Same here on centos 7.2

[root@dcosa16 codes]# go version
go version go1.6 linux/amd64
[root@dcosa16 codes]# uname -a
Linux dcosa16 3.10.0-327.10.1.el7.x86_64 #1 SMP Tue Feb 16 17:03:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
[root@dcosa16 codes]#  go get github.com/yp-engineering/rbd-docker-plugin
go/bin/src/github.com/yp-engineering/rbd-docker-plugin/main.go:83: cannot use d (type cephRBDVolumeDriver) as type volume.Driver in argument to volume.NewHandler:
    cephRBDVolumeDriver does not implement volume.Driver (missing Capabilities method)

**Comment by pineking** [comment]
still the same error

**Comment by jiamliang** [comment]
still the same error  +1

**Comment by tanmx** [comment]
still the same error +1
[root@localhost ~]# docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
[root@localhost ~]# uname -a
Linux localhost 3.10.0-327.22.2.el7.x86_64 #1 SMP Thu Jun 23 17:05:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost ~]# go version
go version go1.6.3 linux/amd64

**Comment by porcupie** [comment]
All the +1 are not actually reading this ticket - likely what you actually have is a #41 

The OP ticket issue has already been resolved. locking this issue now.
