### ISSUE TITLE
Issue when install this plugin: fatal error: rados/librados.h Centos 7.2

### ISSUE THREAD

**Issue by phamthanhnhan14** [yp-engineering/rbd-docker-plugin#25]
Hi ,
I try to install this plugin with command:
**go get github.com/yp-engineering/rbd-docker-plugin**
_# github.com/noahdesu/go-ceph/rados
src/github.com/noahdesu/go-ceph/rados/conn.go:5:29: fatal error: rados/librados.h: No such file or directory
 // #include <rados/librados.h>
                             ^
compilation terminated._

I have googled it but can't find a good resovle for this case.
Please take it easy.
Thanks,
Nhan Pham T.

**Comment by rmartinez3** [comment]
make sure to have librados2-devel and librbd1-devel

if not follow this link to see how to install it 
http://docs.ceph.com/docs/hammer/rados/api/librados-intro/

this should fix the issue. It fix the issue for me 

however now im getting a different error when doing a go get 

`# github.com/yp-engineering/rbd-docker-plugin
  2 src/github.com/yp-engineering/rbd-docker-plugin/main.go:83: cannot use d (type cephRBDVolumeDriver) as type "github.com/docker/go-plugins-helpers/volume".Driver in argument to "github.com/docker/go-pl    ugins-helpers/volume".NewHa:
  3         cephRBDVolumeDriver does not implement "github.com/docker/go-plugins-helpers/volume".Driver (missing Get method)`

**Comment by mrapczynski** [comment]
I'm getting the same error also on Centos 7.2, but this time using the release candidate for Ceph 10.x (Jewel).

**Comment by rmartinez3** [comment]
The problem here is more of a missing function dependency for the docker plugin. docker version +9 will not work with this plugin since need to implement the method that is missing . This issue has been noted by https://github.com/yp-engineering/rbd-docker-plugin/issues/23.

I think there are pulll requests waiting to merge to fix this problem 

https://github.com/yp-engineering/rbd-docker-plugin/pull/24

**Comment by mrapczynski** [comment]
@rmartinez3 Great that explains a lot because I am on 1.10 as well. Thanks!

**Comment by hekaldama** [comment]
Try latest and see if that fixes you. If not, reopen with details. Thanks!

**Comment by mrapczynski** [comment]
@hekaldama OK build works as expected. I'm a first time user of the plugin so getting a strange error, and not sure where to go with it. When I checked Ceph afterwards, my RBD image test1 did get created.

I tried creating a test container as follows:

`docker run -i -t --volume-driver=rbd -v test1:/mnt/test1 centos:6.7 bash`

... and got the following back after 20 seconds or so ...

```
docker: Error response from daemon:
Post http://%2Frun%2Fdocker%2Fplugins%2Frbd.sock/VolumeDriver.Mount: http: ContentLength=17 with Body length 0.
```

The following was reported by the plugin in the logs:

```
rbd-volume-plugin: 2016/04/13 11:58:16 driver.go:440: INFO: Path request(test1) => /var/lib/docker-volumes/rbd/docker/test1
rbd-volume-plugin: 2016/04/13 11:58:16 driver.go:440: INFO: Path request(test1) => /var/lib/docker-volumes/rbd/docker/test1
rbd-volume-plugin: 2016/04/13 11:58:16 driver.go:440: INFO: Path request(test1) => /var/lib/docker-volumes/rbd/docker/test1
rbd-volume-plugin: 2016/04/13 11:58:16 driver.go:440: INFO: Path request(test1) => /var/lib/docker-volumes/rbd/docker/test1
rbd-volume-plugin: 2016/04/13 11:58:16 driver.go:440: INFO: Path request(test1) => /var/lib/docker-volumes/rbd/docker/test1
rbd-volume-plugin: 2016/04/13 11:58:16 driver.go:269: INFO: Mount(test1)
rbd-volume-plugin: 2016/04/13 11:58:16 driver.go:681: INFO: rbdImageExists(docker/test1)
rbd-volume-plugin: 2016/04/13 11:58:16 driver.go:289: WARN: Image does not exist: test1
rbd-volume-plugin: 2016/04/13 11:58:16 driver.go:135: INFO: createImage(test1)
rbd-volume-plugin: 2016/04/13 11:58:16 driver.go:681: INFO: rbdImageExists(docker/test1)
rbd-volume-plugin: 2016/04/13 11:58:16 driver.go:705: INFO: Attempting to create RBD Image: (%s/%s, %s, %s) docker test1 256000 xfs
rbd-volume-plugin: 2016/04/13 11:58:16 driver.go:818: INFO: lockImage(docker/test1)
rbd-volume-plugin: 2016/04/13 11:58:17 main.go:70: INFO: Setting up Ceph Driver for PluginID=rbd, cluster=, user=admin, pool=docker, mount=/var/lib/docker-volumes, config=
rbd-volume-plugin: 2016/04/13 11:58:17 driver.go:83: INFO: newCephRBDVolumeDriver: setting base mount dir=/var/lib/docker-volumes/rbd
rbd-volume-plugin: 2016/04/13 11:58:17 driver.go:554: INFO: connecting to Ceph and default pool context
rbd-volume-plugin: 2016/04/13 11:58:17 main.go:82: INFO: Creating Docker VolumeDriver Handler
rbd-volume-plugin: 2016/04/13 11:58:17 main.go:86: INFO: Opening Socket for Docker to connect: /run/docker/plugins/rbd.sock
rbd-volume-plugin: 2016/04/13 11:58:32 driver.go:459: INFO: Unmount(test1)
rbd-volume-plugin: 2016/04/13 11:58:32 driver.go:477: WARN: Volume is not in known mounts: will attempt limited Unmount: test1
rbd-volume-plugin: 2016/04/13 11:58:32 driver.go:492: ERROR: unmounting device(/dev/rbd/docker/test1): exit status 32
rbd-volume-plugin: 2016/04/13 11:58:32 driver.go:500: ERROR: unmapping image device(/dev/rbd/docker/test1): exit status 22
rbd-volume-plugin: 2016/04/13 11:58:32 driver.go:861: INFO: unlockImage(docker/test1, dockertest.ad.fhda.edu)
rbd-volume-plugin: 2016/04/13 11:58:32 driver.go:508: ERROR: unlocking RBD image(test1): RBD image not found
rbd-volume-plugin: 2016/04/13 11:58:32 driver.go:440: INFO: Path request(test1) => /var/lib/docker-volumes/rbd/docker/test1
rbd-volume-plugin: 2016/04/13 11:58:32 driver.go:383: INFO: List request => []
rbd-volume-plugin: 2016/04/13 11:58:33 driver.go:440: INFO: Path request(test1) => /var/lib/docker-volumes/rbd/docker/test1
rbd-volume-plugin: 2016/04/13 11:58:33 driver.go:440: INFO: Path request(test1) => /var/lib/docker-volumes/rbd/docker/test1
rbd-volume-plugin: 2016/04/13 11:58:33 driver.go:440: INFO: Path request(test1) => /var/lib/docker-volumes/rbd/docker/test1
```

**Comment by hekaldama** [comment]
I am unsure what is going on at this time. I will continue to look at this, but I recommend using the supported versions of ceph + kernel / distro described:

http://docs.ceph.com/docs/master/start/os-recommendations/

and pairing that with docker 1.10 or newer. That is what I am going to be testing now.

**Comment by hekaldama** [comment]
Tested to be working with:

```
$ cat /etc/redhat-release && uname -r && docker --version && go version && ceph --version
CentOS Linux release 7.2.1511 (Core) 
3.10.0-327.3.1.el7.x86_64
Docker version 1.10.2, build c3959b1
go version go1.6.1 linux/amd64
ceph version 0.94.2 (5fb85614ca8f354284c713a2f9c610860720bbf3)
```

running [micro-osd.sh](https://github.com/yp-engineering/rbd-docker-plugin/blob/master/micro-osd.sh) like:

```
$ micro-osd.sh tmp
```

and starting `rbd-docker-plugin` with:

```
# rbd-docker-plugin -create=true -config=tmp/ceph.conf
```

and then ran your example of:

```
$ docker run -i -t --volume-driver=rbd -v test1:/mnt/test1 centos:6.7 bash
```

which ran without error.

**Comment by hekaldama** [comment]
Will try with different kernel tomorrow.

**Comment by mrapczynski** [comment]
@hekaldama OK thanks. My OS and Docker version are the same except that I'm running a release candidate of Jewel for Ceph, 10.1.1 - so that could be the issue. Thus far, this new version of Ceph has been flawless.

I can mount and use the same RBD images right on the host without issues - so whatever is breaking seems to be limited to the automation provided by the plugin. Also, it may be useful to know that the plugin leaves an image locked after it gives up and quits. I've had to use `rbd` to manually unlock it each time.

**Comment by ranjithamca** [comment]
Hi, 
  I try to test rbd-docker-plugin
  i start the  rbd-docker plugin  with 
      **rbd-docker-plugin --create --user=docker --pool=docker --config=/etc/ceph/ceph.conf**
I ran the docker 
   **docker run -i -t --volume-driver=rbd --volume test4:/mnt/test4 centos:6.7 bash** 
The following error occur
docker: Error response from daemon: create test4: Post http://%2Frun%2Fdocker%2Fplugins%2Frbd.sock/VolumeDriver.Create: dial unix /run/docker/plugins/rbd.sock: connect: connection refused.



At the time the rbd-docker plugin shows the panic error


rbd-volume-plugin: 2016/07/14 03:11:40 main.go:70: INFO: Setting up Ceph Driver for PluginID=rbd, cluster=, user=docker, pool=docker, mount=/var/lib/docker-volumes, config=/etc/ceph/ceph.conf
rbd-volume-plugin: 2016/07/14 03:11:40 driver.go:83: INFO: newCephRBDVolumeDriver: setting base mount dir=/var/lib/docker-volumes/rbd
rbd-volume-plugin: 2016/07/14 03:11:40 driver.go:590: INFO: connecting to Ceph and default pool context
rbd-volume-plugin: 2016/07/14 03:11:40 main.go:83: INFO: Creating Docker VolumeDriver Handler
rbd-volume-plugin: 2016/07/14 03:11:40 main.go:87: INFO: Opening Socket for Docker to connect: /run/docker/plugins/rbd.sock
rbd-volume-plugin: 2016/07/14 03:12:41 driver.go:686: DEBUG: parseImagePoolNameSize: "test4": ["test4" "" "" "test4" "" ""]
rbd-volume-plugin: 2016/07/14 03:12:41 driver.go:717: INFO: rbdImageExists(docker/test4)
rbd-volume-plugin: 2016/07/14 03:12:41 driver.go:733: INFO: Ceph RBD Image ('test4') not found: RBD image not found
rbd-volume-plugin: 2016/07/14 03:12:41 driver.go:433: WARN: Image test4 does not exist
rbd-volume-plugin: 2016/07/14 03:12:41 driver.go:136: INFO: Create({"test4" map[] ""})
rbd-volume-plugin: 2016/07/14 03:12:41 driver.go:144: INFO: createImage({"test4" map[] ""})
rbd-volume-plugin: 2016/07/14 03:12:41 driver.go:686: DEBUG: parseImagePoolNameSize: "test4": ["test4" "" "" "test4" "" ""]
rbd-volume-plugin: 2016/07/14 03:12:41 driver.go:717: INFO: rbdImageExists(docker/test4)
rbd-volume-plugin: 2016/07/14 03:12:42 driver.go:733: INFO: Ceph RBD Image ('test4') not found: RBD image not found
rbd-volume-plugin: 2016/07/14 03:12:42 driver.go:743: INFO: Attempting to create RBD Image: (%s/%s, %s, %s) docker test4 20480 xfs
rbd-volume-plugin: 2016/07/14 03:12:42 driver.go:1007: DEBUG: sh CMD: &{"/usr/bin/rbd" ["rbd" "create" "--id" "docker" "--pool" "docker" "--image-format" "2" "--size" "20480" "test4"] [] "" <nil> <nil> <nil> [] %!q(*syscall.SysProcAttr=<nil>) %!q(*os.Process=<nil>) "<nil>" <nil> %!q(bool=false) [] [] [] [] %!q(chan error=<nil>)}
rbd-volume-plugin: 2016/07/14 03:12:42 driver.go:856: INFO: lockImage(docker/test4)
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x0 pc=0x7f0e26afc4d7]

runtime stack:
runtime.throw(0x8cac00, 0x2a)
	/home/megdc/go/src/runtime/panic.go:530 +0x90
runtime.sigpanic()
	/home/megdc/go/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 7 [syscall, locked to thread]:
runtime.cgocall(0x703220, 0xc820128ed0, 0x10000c800000000)
	/home/megdc/go/src/runtime/cgocall.go:123 +0x11b fp=0xc820128e98 sp=0xc820128e68
github.com/ceph/go-ceph/rbd._Cfunc_rbd_lock_exclusive(0x7f0e04000b40, 0x7f0e040008c0, 0x0)
	??:0 +0x41 fp=0xc820128ed0 sp=0xc820128e98
github.com/ceph/go-ceph/rbd.(*Image).LockExclusive(0xc820129060, 0xc82000f462, 0xb, 0x0, 0x0)
	/home/megdc/go/bin/src/github.com/ceph/go-ceph/rbd/rbd.go:572 +0x15b fp=0xc820128f50 sp=0xc820128ed0
main.(*cephRBDVolumeDriver).lockImage(0xc8201295b0, 0x7ffcf824d94b, 0x6, 0xc8200f2400, 0x5, 0x0, 0x0, 0x0, 0x0)
	/home/megdc/go/bin/src/github.com/ranjithamca/rbd-docker-plugin/driver.go:877 +0x619 fp=0xc8201290e0 sp=0xc820128f50
main.(*cephRBDVolumeDriver).createRBDImage(0xc8201295b0, 0x7ffcf824d94b, 0x6, 0xc8200f2400, 0x5, 0x5000, 0x84c088, 0x3, 0x0, 0x0)
	/home/megdc/go/bin/src/github.com/ranjithamca/rbd-docker-plugin/driver.go:771 +0x89c fp=0xc820129390 sp=0xc8201290e0
main.cephRBDVolumeDriver.createImage(0x84b3d8, 0x3, 0x0, 0x0, 0x7ffcf824d93d, 0x6, 0x7ffcf824d94b, 0x6, 0xc8200c28c0, 0x1b, ...)
	/home/megdc/go/bin/src/github.com/ranjithamca/rbd-docker-plugin/driver.go:192 +0xe9f fp=0xc8201295b0 sp=0xc820129390
main.cephRBDVolumeDriver.Create(0x84b3d8, 0x3, 0x0, 0x0, 0x7ffcf824d93d, 0x6, 0x7ffcf824d94b, 0x6, 0xc8200c28c0, 0x1b, ...)
	/home/megdc/go/bin/src/github.com/ranjithamca/rbd-docker-plugin/driver.go:140 +0x20a fp=0xc820129760 sp=0xc8201295b0
main.(*cephRBDVolumeDriver).Create(0xc820080280, 0xc8200f2400, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	<autogenerated>:1 +0x112 fp=0xc8201298b0 sp=0xc820129760
github.com/docker/go-plugins-helpers/volume.(*Handler).initMux.func1(0xc8200f2400, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/megdc/go/bin/src/github.com/docker/go-plugins-helpers/volume/api.go:80 +0xa3 fp=0xc820129998 sp=0xc8201298b0
github.com/docker/go-plugins-helpers/volume.(*Handler).handle.func1(0x7f0e39af41b8, 0xc8200ec820, 0xc820132000)
	/home/megdc/go/bin/src/github.com/docker/go-plugins-helpers/volume/api.go:118 +0xd8 fp=0xc820129ae8 sp=0xc820129998
net/http.HandlerFunc.ServeHTTP(0xc82000f300, 0x7f0e39af41b8, 0xc8200ec820, 0xc820132000)
	/home/megdc/go/src/net/http/server.go:1618 +0x3a fp=0xc820129b08 sp=0xc820129ae8
net/http.(*ServeMux).ServeHTTP(0xc820065170, 0x7f0e39af41b8, 0xc8200ec820, 0xc820132000)
	/home/megdc/go/src/net/http/server.go:1910 +0x17d fp=0xc820129b60 sp=0xc820129b08
net/http.serverHandler.ServeHTTP(0xc8200ea000, 0x7f0e39af41b8, 0xc8200ec820, 0xc820132000)
	/home/megdc/go/src/net/http/server.go:2081 +0x19e fp=0xc820129bc0 sp=0xc820129b60
net/http.(*conn).serve(0xc820080400)
	/home/megdc/go/src/net/http/server.go:1472 +0xf2e fp=0xc820129f88 sp=0xc820129bc0
runtime.goexit()
	/home/megdc/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820129f90 sp=0xc820129f88
created by net/http.(*Server).Serve
	/home/megdc/go/src/net/http/server.go:2137 +0x44e

goroutine 1 [IO wait]:
net.runtime_pollWait(0x7f0e39af4028, 0x72, 0x0)
	/home/megdc/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8200f4060, 0x72, 0x0, 0x0)
	/home/megdc/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200f4060, 0x0, 0x0)
	/home/megdc/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8200f4000, 0x0, 0x7f0e39af40e8, 0xc8200c2a00)
	/home/megdc/go/src/net/fd_unix.go:426 +0x27c
net.(*UnixListener).AcceptUnix(0xc8200ee0c0, 0xc82004d938, 0x0, 0x0)
	/home/megdc/go/src/net/unixsock_posix.go:305 +0x53
net.(*UnixListener).Accept(0xc8200ee0c0, 0x0, 0x0, 0x0, 0x0)
	/home/megdc/go/src/net/unixsock_posix.go:315 +0x41
net/http.(*Server).Serve(0xc8200ea000, 0x7f0e39af3080, 0xc8200ee0c0, 0x0, 0x0)
	/home/megdc/go/src/net/http/server.go:2117 +0x129
github.com/docker/go-plugins-helpers/sdk.Handler.listenAndServe(0xc820065170, 0x84be00, 0x4, 0xc8200c2940, 0x1c, 0x0, 0x0, 0x0, 0x0)
	/home/megdc/go/bin/src/github.com/docker/go-plugins-helpers/sdk/handler.go:82 +0x288
github.com/docker/go-plugins-helpers/sdk.Handler.ServeUnix(0xc820065170, 0x0, 0x0, 0xc8200c2940, 0x1c, 0x0, 0x0)
	/home/megdc/go/bin/src/github.com/docker/go-plugins-helpers/sdk/handler.go:48 +0x6d
main.main()
	/home/megdc/go/bin/src/github.com/ranjithamca/rbd-docker-plugin/main.go:122 +0xe3f

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/home/megdc/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/home/megdc/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/home/megdc/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/home/megdc/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [select, locked to thread]:
runtime.gopark(0x8fc500, 0xc82002a728, 0x84b7d8, 0x6, 0x18, 0x2)
	/home/megdc/go/src/runtime/proc.go:262 +0x163
runtime.selectgoImpl(0xc82002a728, 0x0, 0x18)
	/home/megdc/go/src/runtime/select.go:392 +0xa67
runtime.selectgo(0xc82002a728)
	/home/megdc/go/src/runtime/select.go:215 +0x12
runtime.ensureSigM.func1()
	/home/megdc/go/src/runtime/signal1_unix.go:279 +0x358
runtime.goexit()
	/home/megdc/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 18 [chan receive]:
main.main.func1(0xc820062480, 0xc820080200, 0xc82002c038, 0xc82000f200)
	/home/megdc/go/bin/src/github.com/ranjithamca/rbd-docker-plugin/main.go:100 +0x72
created by main.main
	/home/megdc/go/bin/src/github.com/ranjithamca/rbd-docker-plugin/main.go:119 +0xdf7
