### ISSUE TITLE
Can not compile plugin with docker 1.10+ - missing Capabilities Volume API method

### ISSUE THREAD

**Issue by jianghaitao** [yp-engineering/rbd-docker-plugin#41]
I would like to test out the plugin but it failed to compile as one can see below. Would appreciate any help. Thanks.

```
# go version
go version go1.6 linux/amd64

# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"

# ceph -v
ceph version 0.94.7 (d56bdf93ced6b80b07397d57e3fa68fe68304432)

# go get github.com/yp-engineering/rbd-docker-plugin
# github.com/yp-engineering/rbd-docker-plugin
../src/github.com/yp-engineering/rbd-docker-plugin/main.go:83: cannot use d (type cephRBDVolumeDriver) as type volume.Driver in argument to volume.NewHandler:
        cephRBDVolumeDriver does not implement volume.Driver (missing Capabilities method)

```

**Comment by porcupie** [comment]
Have not seen this error before - but FYI golang 1.6 is not generally supported due to stricter http HOST header checks.  Really depends on your docker version and whether docker daemon sending correct HOST header yet.

Also looks like you are using a much newer version of the volume helpers, which has some new `Capabilities` method on the volume.Driver interface, which we do not yet support.

**Comment by de1m** [comment]
I've the same error with go 1.6 on ubuntu 14.04
`DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"
`

`src/github.com/yp-engineering/rbd-docker-plugin/main.go:83: cannot use d (type cephRBDVolumeDriver) as type volume.Driver in argument to volume.NewHandler:
        cephRBDVolumeDriver does not implement volume.Driver (missing Capabilities method)
`

**Comment by jiamliang** [comment]
I've the same error with go 1.6 on ubuntu 16.04

# github.com/yp-engineering/rbd-docker-plugin

../../../yp-engineering/rbd-docker-plugin/main.go:83: cannot use d (type cephRBDVolumeDriver) as type volume.Driver in argument to volume.NewHandler:
    cephRBDVolumeDriver does not implement volume.Driver (missing Capabilities method)

**Comment by porcupie** [comment]
We don't (yet) support docker 1.10 nor the new volume-driver plugin "Capabilities" method. Workaround until we add something proper is to downgrade the docker client libraries and docker volume helpers to < docker volume api 1.10.

**Comment by porcupie** [comment]
Looks like the `Capabilities` method was [added in docker 1.12](https://docs.docker.com/engine/extend/plugins_volume/#/1-12-0).

According to the documentation in [the pull request for `Capabilities` method](https://github.com/docker/docker/pull/22077), we should return the following to indicate that Ceph RBD volumes managed by this plugin are _global_ to the cluster: 

``` json
{
  "Capabilities": {
    "Scope": "global"
  }
}
```

**Comment by linuxwind** [comment]
hi, when will be fix it?

**Comment by porcupie** [comment]
Fixed already
