### ISSUE TITLE
Static build: help needed

### ISSUE THREAD

**Issue by h0tbird** [yp-engineering/rbd-docker-plugin#9]
I am trying to statically compile `rbd-docker-plugin` in order to run this driver in `CoreOS`.
My best attempt is to edit the Makefile and replace this line:

```
go build -v -x -o dist/$(BINARY) .
```

with this other line:

```
go build -a -tags netgo --ldflags '-extldflags "-static --verbose"' -v -x -o dist/$(BINARY) .
```

but I get this error:

```
/usr/bin/ld: cannot find -lrados
/usr/bin/ld: cannot find -lrados
/usr/bin/ld: cannot find -lrados
/usr/bin/ld: cannot find -lrbd
collect2: error: ld returned 1 exit status
```

I also tried this with no luck:

```
go build -a -tags netgo --ldflags '-extldflags "-lrados -lrbd -static --verbose"' -v -x -o dist/$(BINARY) .
```

Any idea?

**Comment by hekaldama** [comment]
Not my forte either, but will take a look. I cannot get the same error on Ubuntu yet (at least that I can find).

**Comment by hekaldama** [comment]
I don't think your system can find the libs you are trying to link, I get an entirely different ST or whatever it is. The output I get from your last line above is > 20MB of text. Still reading through it.

**Comment by hekaldama** [comment]
I am getting a ton of errors from librados.a. Maybe we should chat on freenode about this. My handle is hekaldama.

**Comment by hekaldama** [comment]
I am also unsure if this is even possible with the limited googling around 'getaddrinfo' and glibc.

**Comment by h0tbird** [comment]
@hekaldama thank you for trying. I read somewhere that `-tags netgo` might help with the `getaddrinfo` problem. Anyway not my forte either.

I have decided to [re-write](https://github.com/h0tbird/docker-volume-rbd) this driver myself because:
- I want to learn Go.
- It is a missing piece in my docker-aware stack and I need to make it work with CoreOS.

I am basically coping and pasting from your code and also from contiv/volplugin.
Let me know how you want me to reflect that in the license / credits.
